// MuscleWiki'den (piyasa araştırması, kod/görsel kopyalanmadı) ilham alınan
// kürate edilmiş egzersiz referans kütüphanesi. Kullanıcının kendi
// `exercises` tablosundan (tamamen serbest metin, "dayatma yok" ilkesiyle)
// BİLİNÇLİ OLARAK AYRI — roadmapTemplates.ts/onboardingTemplates.ts ile
// aynı desen: statik, uygulamanın sağladığı referans veri, DB tablosu değil.
// Kas Haritası filtrelemesi ve AI antrenman modları (Bölüm 2) buradan
// gerçek isimler seçiyor, AI egzersiz uydurmuyor.
export type MuscleGroup =
  | "chest"
  | "back"
  | "shoulders"
  | "biceps"
  | "triceps"
  | "forearms"
  | "abs"
  | "obliques"
  | "quads"
  | "hamstrings"
  | "glutes"
  | "calves"
  | "traps";

export type EquipmentType = "bodyweight" | "dumbbell" | "barbell" | "cable" | "machine" | "band" | "kettlebell";

export type ExerciseDifficulty = "beginner" | "intermediate" | "advanced";

export interface LibraryExercise {
  id: string;
  name: string;
  muscleGroup: MuscleGroup;
  secondaryMuscles: MuscleGroup[];
  equipment: EquipmentType;
  difficulty: ExerciseDifficulty;
  instructions: string;
}

export const MUSCLE_GROUP_LABELS: Record<MuscleGroup, string> = {
  chest: "Göğüs",
  back: "Sırt",
  shoulders: "Omuz",
  biceps: "Biceps",
  triceps: "Triceps",
  forearms: "Önkol",
  abs: "Karın",
  obliques: "Yan Karın",
  quads: "Ön Uyluk",
  hamstrings: "Arka Uyluk",
  glutes: "Kalça",
  calves: "Baldır",
  traps: "Trapez",
};

export const EQUIPMENT_LABELS: Record<EquipmentType, string> = {
  bodyweight: "Vücut Ağırlığı",
  dumbbell: "Dambıl",
  barbell: "Halter",
  cable: "Kablo",
  machine: "Makine",
  band: "Direnç Bandı",
  kettlebell: "Kettlebell",
};

export const DIFFICULTY_LABELS: Record<ExerciseDifficulty, string> = {
  beginner: "Başlangıç",
  intermediate: "Orta",
  advanced: "İleri",
};

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // Göğüs
  {
    id: "barbell-bench-press",
    name: "Halter Bench Press",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Sırt üstü bankta, omuz genişliğinden biraz geniş kavrayışla halteri göğüs hizasına indir, patlayıcı şekilde yukarı it.",
  },
  {
    id: "dumbbell-bench-press",
    name: "Dambıl Bench Press",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Sırt üstü bankta, iki dambılı göğüs hizasından yukarı doğru it, tepede hafifçe birbirine yaklaştır.",
  },
  {
    id: "incline-bench-press",
    name: "Eğik Bench Press",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "30-45 derece eğik bankta, üst göğüsü hedefleyerek haltri göğüs üstüne indir ve it.",
  },
  {
    id: "dumbbell-fly",
    name: "Dambıl Fly",
    muscleGroup: "chest",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Sırt üstü, dirsekleri hafif kırık tutarak dambılları göğüs hizasından yanlara aç, sonra kavis çizerek yukarı topla.",
  },
  {
    id: "push-up",
    name: "Şınav",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders", "abs"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Plank pozisyonunda, gövdeni düz tutarak göğsün yere yaklaşana kadar in, sonra it.",
  },
  {
    id: "cable-crossover",
    name: "Kablo Crossover",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "intermediate",
    instructions: "İki kablo istasyonu arasında, kolları hafif kırık tutarak kabloları önde birleştir.",
  },
  {
    id: "chest-press-machine",
    name: "Chest Press Makinesi",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps"],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Makinede sırtın sabit, kolçakları göğüs hizasından öne it, kontrollü geri getir.",
  },
  {
    id: "dips-chest",
    name: "Dips (Göğüs Ağırlıklı)",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    difficulty: "advanced",
    instructions: "Paralel barlarda, gövdeni öne eğerek göğsü daha çok hedefleyip in-çık yap.",
  },

  // Sırt
  {
    id: "deadlift",
    name: "Deadlift (Ölü Kaldırış)",
    muscleGroup: "back",
    secondaryMuscles: ["hamstrings", "glutes", "traps"],
    equipment: "barbell",
    difficulty: "advanced",
    instructions: "Sırt düz, halteri yerden kalça ve sırt gücüyle kaldır, tepede kalçayı tam aç.",
  },
  {
    id: "pull-up",
    name: "Barfiks",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "bodyweight",
    difficulty: "advanced",
    instructions: "Bardan omuz genişliğinde asılı, çeneni bar üstüne çıkana kadar kendini çek.",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Geniş kavrayışla barı göğüs üstüne doğru çek, omuzları aşağı-geriye sık.",
  },
  {
    id: "barbell-row",
    name: "Halter Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "traps"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Gövde öne eğik, sırt düz, halteri karın hizasına doğru çek.",
  },
  {
    id: "dumbbell-row",
    name: "Tek Kol Dambıl Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Bir el ve diz bankta destekli, diğer elde dambılı kalçaya doğru çek.",
  },
  {
    id: "seated-cable-row",
    name: "Oturarak Kablo Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Dik otur, kabloyu karına doğru çek, omuz bıçaklarını sık.",
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "traps"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Gövde öne eğik, T-bar tutamağını göğse doğru çek.",
  },
  {
    id: "face-pull",
    name: "Face Pull",
    muscleGroup: "back",
    secondaryMuscles: ["shoulders", "traps"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "İp tutamağı yüz hizasına doğru çek, dirsekleri yüksek tut, omuz sağlığı için iyi.",
  },
  {
    id: "hyperextension",
    name: "Hyperextension",
    muscleGroup: "back",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Hyperextension bankında, kalçadan öne eğilip alt sırt gücüyle gövdeyi düzelt.",
  },

  // Omuz
  {
    id: "overhead-press",
    name: "Halter Overhead Press",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Ayakta, halteri omuzdan başın üstüne it, kor kaslarını sık.",
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dambıl Omuz Press",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Oturarak veya ayakta, iki dambılı omuzdan başın üstüne it.",
  },
  {
    id: "lateral-raise",
    name: "Yana Kaldırış",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Dambılları hafif kırık kollarla yanlara omuz hizasına kadar kaldır.",
  },
  {
    id: "front-raise",
    name: "Öne Kaldırış",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Dambılları öne doğru omuz hizasına kadar kaldır.",
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Dambıllar avuç içi sana bakacak şekilde başlayıp iterken dışa döndür.",
  },
  {
    id: "rear-delt-fly",
    name: "Arka Omuz Fly",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Öne eğik gövdeyle dambılları yanlara açarak arka omuzu hedefle.",
  },
  {
    id: "upright-row",
    name: "Upright Row",
    muscleGroup: "shoulders",
    secondaryMuscles: ["traps"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Halteri veya dambılları çeneye doğru dirsekler yüksekte çek.",
  },

  // Biceps
  {
    id: "barbell-curl",
    name: "Halter Curl",
    muscleGroup: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Dirsekleri sabit tutarak halteri omuza doğru kıvır.",
  },
  {
    id: "dumbbell-curl",
    name: "Dambıl Curl",
    muscleGroup: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Dirsekleri sabit tutarak dambılları tek tek veya birlikte omuza kıvır.",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscleGroup: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Dambılları çekiç tutuşuyla (avuç içi içe bakar) kıvır.",
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Preacher bankında kolun arkası sabitken kıvır, tam kontraksiyon sağlar.",
  },
  {
    id: "cable-curl",
    name: "Kablo Curl",
    muscleGroup: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Alt kasnaktan düz bar tutamağıyla dirsekleri sabit tutarak kıvır.",
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Oturarak, dirseği uyluğa dayayıp tek kol dambılı kıvır, izole hareket.",
  },

  // Triceps
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    muscleGroup: "triceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Dirsekleri gövdeye sabit tutarak kabloyu aşağı it.",
  },
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    muscleGroup: "triceps",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Sırt üstü, halteri alına doğru indirip dirsekten geri it.",
  },
  {
    id: "close-grip-bench-press",
    name: "Dar Kavrayışlı Bench Press",
    muscleGroup: "triceps",
    secondaryMuscles: ["chest"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Omuz genişliğinden dar kavrayışla bench press yap, dirsekler gövdeye yakın.",
  },
  {
    id: "overhead-triceps-extension",
    name: "Başüstü Triceps Extension",
    muscleGroup: "triceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Tek dambılı iki elle başın arkasına indir, dirsekten geri it.",
  },
  {
    id: "dips-triceps",
    name: "Dips (Triceps Ağırlıklı)",
    muscleGroup: "triceps",
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "bodyweight",
    difficulty: "advanced",
    instructions: "Paralel barlarda gövdeyi dik tutarak in-çık yap, tricepsi daha çok hedefler.",
  },
  {
    id: "triceps-kickback",
    name: "Triceps Kickback",
    muscleGroup: "triceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Öne eğik gövdeyle, dirseği sabit tutup dambılı arkaya doğru it.",
  },

  // Önkol
  {
    id: "wrist-curl",
    name: "Bilek Curl",
    muscleGroup: "forearms",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Kol dizde destekli, dambılı sadece bilekten kıvır.",
  },
  {
    id: "reverse-wrist-curl",
    name: "Ters Bilek Curl",
    muscleGroup: "forearms",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Avuç içi aşağı bakarken bilekten yukarı kıvır.",
  },
  {
    id: "farmers-walk",
    name: "Farmer's Walk",
    muscleGroup: "forearms",
    secondaryMuscles: ["traps", "abs"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Ağır dambıl/kettlebell çiftini iki elde tutarak dik duruşla yürü.",
  },
  {
    id: "reverse-curl",
    name: "Ters Curl",
    muscleGroup: "forearms",
    secondaryMuscles: ["biceps"],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Avuç içi aşağı bakan kavrayışla halteri kıvır.",
  },

  // Karın
  {
    id: "crunch",
    name: "Mekik (Crunch)",
    muscleGroup: "abs",
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Sırt üstü, dizler kırık, omuzları yerden kaldırarak karnı sık.",
  },
  {
    id: "plank",
    name: "Plank",
    muscleGroup: "abs",
    secondaryMuscles: ["obliques"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Dirsekler ve ayak uçları üzerinde, gövdeyi düz bir çizgide sabit tut.",
  },
  {
    id: "leg-raise",
    name: "Bacak Kaldırış",
    muscleGroup: "abs",
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Sırt üstü, bacakları düz tutarak yukarı kaldır, kontrollü indir.",
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    muscleGroup: "abs",
    secondaryMuscles: ["obliques"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Oturarak hafif geriye yaslan, gövdeyi sağa-sola çevir.",
  },
  {
    id: "cable-crunch",
    name: "Kablo Crunch",
    muscleGroup: "abs",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "intermediate",
    instructions: "Diz üstü, ip tutamağını başın yanında tutup karından kıvrılarak in.",
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    muscleGroup: "abs",
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Plank pozisyonunda dizleri sırayla göğse doğru hızlıca çek.",
  },
  {
    id: "hanging-knee-raise",
    name: "Asılı Diz Kaldırış",
    muscleGroup: "abs",
    secondaryMuscles: ["forearms"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Bardan asılı, dizleri karına doğru kaldır.",
  },

  // Yan Karın
  {
    id: "side-plank",
    name: "Yan Plank",
    muscleGroup: "obliques",
    secondaryMuscles: ["abs"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Tek dirsek ve ayak yan yana üzerinde, gövdeyi düz bir çizgide tut.",
  },
  {
    id: "woodchopper",
    name: "Woodchopper",
    muscleGroup: "obliques",
    secondaryMuscles: ["abs"],
    equipment: "cable",
    difficulty: "intermediate",
    instructions: "Kabloyu çapraz, yukarıdan aşağıya (veya tersi) gövdeyi döndürerek çek.",
  },
  {
    id: "bicycle-crunch",
    name: "Bisiklet Crunch",
    muscleGroup: "obliques",
    secondaryMuscles: ["abs"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Sırt üstü, dirsek-diz çaprazlamasını bisiklet pedalı gibi sırayla yap.",
  },
  {
    id: "side-bend",
    name: "Yana Eğilme",
    muscleGroup: "obliques",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Ayakta, elde dambılla gövdeyi yana eğ, yan karını hisset.",
  },

  // Ön Uyluk
  {
    id: "squat",
    name: "Squat (Çömelme)",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Halter sırt üstünde, kalça geriye ve aşağı, dizler ayak ucunu geçmeden çök, kalk.",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Makinede ayaklar omuz genişliğinde, dizleri göğse doğru indir, it.",
  },
  {
    id: "lunge",
    name: "Lunge (Hamle Adımı)",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Bir adım öne çık, arka diz yere yakın inene kadar çök, geri dön.",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgar Split Squat",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Arka ayak bank üzerinde, ön bacakla tek bacak squat yap.",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    muscleGroup: "quads",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Makinede oturarak dizleri düz olana kadar bacakları kaldır.",
  },
  {
    id: "front-squat",
    name: "Front Squat",
    muscleGroup: "quads",
    secondaryMuscles: ["abs", "glutes"],
    equipment: "barbell",
    difficulty: "advanced",
    instructions: "Halter ön omuzlarda, dik gövdeyle çök, quadsi daha çok hedefler.",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Dambılı göğüs önünde iki elle tutarak çök.",
  },
  {
    id: "step-up",
    name: "Step-up",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Bank/kutu üzerine tek bacakla çık, diğer bacağı takip ettir.",
  },

  // Arka Uyluk
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    muscleGroup: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Dizler hafif kırık, kalçadan öne eğilerek halteri bacak boyunca indir, kalçayla kalk.",
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    muscleGroup: "hamstrings",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Makinede yüzüstü veya oturarak topuğu kalçaya doğru kıvır.",
  },
  {
    id: "good-morning",
    name: "Good Morning",
    muscleGroup: "hamstrings",
    secondaryMuscles: ["back", "glutes"],
    equipment: "barbell",
    difficulty: "advanced",
    instructions: "Halter sırt üstünde, kalçadan öne eğilip sırtı düz tutarak geri dön.",
  },
  {
    id: "stiff-leg-deadlift",
    name: "Düz Bacak Deadlift",
    muscleGroup: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Dizler neredeyse düz, kalçadan öne eğilerek halteri indir.",
  },
  {
    id: "glute-ham-raise",
    name: "Glute-Ham Raise",
    muscleGroup: "hamstrings",
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    difficulty: "advanced",
    instructions: "GHR bankında dizden gövdeyi öne indir, hamstring gücüyle geri kalk.",
  },
  {
    id: "nordic-curl",
    name: "Nordic Curl",
    muscleGroup: "hamstrings",
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "advanced",
    instructions: "Ayak bilekleri sabitlenmiş, diz üstünden gövdeyi kontrollü öne indir.",
  },

  // Kalça
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    muscleGroup: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Sırt bankta, halter kalça üstünde, kalçayı tam yukarı it.",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    muscleGroup: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Sırt üstü, dizler kırık, kalçayı yukarı kaldırıp sık.",
  },
  {
    id: "cable-kickback",
    name: "Kablo Kickback",
    muscleGroup: "glutes",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Ayak bileğine bağlı kabloyla bacağı arkaya doğru it.",
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlift",
    muscleGroup: "glutes",
    secondaryMuscles: ["quads", "hamstrings", "back"],
    equipment: "barbell",
    difficulty: "advanced",
    instructions: "Ayaklar geniş, halteri bacak arasından kalça gücüyle kaldır.",
  },
  {
    id: "clamshell",
    name: "Clamshell",
    muscleGroup: "glutes",
    secondaryMuscles: [],
    equipment: "band",
    difficulty: "beginner",
    instructions: "Yan yatarak dizleri kırık, üstteki dizi bant direncine karşı aç.",
  },

  // Baldır
  {
    id: "standing-calf-raise",
    name: "Ayakta Baldır Kaldırış",
    muscleGroup: "calves",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Ayakta, topuklardan yukarı kalkarak baldırı tam sık.",
  },
  {
    id: "seated-calf-raise",
    name: "Oturarak Baldır Kaldırış",
    muscleGroup: "calves",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Oturarak, dizler kırık, topuklardan yukarı kalk.",
  },
  {
    id: "donkey-calf-raise",
    name: "Donkey Baldır Kaldırış",
    muscleGroup: "calves",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "intermediate",
    instructions: "Gövde öne eğik, topuklardan yukarı kalkarak baldırı çalıştır.",
  },
  {
    id: "jump-rope",
    name: "İp Atlama",
    muscleGroup: "calves",
    secondaryMuscles: ["abs"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "İp atlarken ayak uçlarından hafif zıpla, baldırları sürekli çalıştırır.",
  },

  // Trapez
  {
    id: "barbell-shrug",
    name: "Halter Shrug",
    muscleGroup: "traps",
    secondaryMuscles: ["forearms"],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Halteri elde tutarak omuzları kulaklara doğru kaldır.",
  },
  {
    id: "dumbbell-shrug",
    name: "Dambıl Shrug",
    muscleGroup: "traps",
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Dambılları elde tutarak omuzları yukarı kaldır ve sık.",
  },
];
