// Seyahat kategorisi — Türkiye'nin 81 ilinin kanonik Türkçe isim + plaka
// kodu listesi. borders-of-turkey (CC0) GeoJSON'ındaki KML-transliterasyonlu
// isimler ("Agri" gibi) yerine UI'da HER ZAMAN bu liste gösteriliyor —
// GeoJSON sadece poligon geometrisi için kullanılıyor, plaka koduyla
// eşleştiriliyor (bkz. src/lib/travel/turkey-geo-match.ts).
export interface TurkeyProvince {
  plateCode: number;
  name: string;
}

export const TURKEY_PROVINCES: TurkeyProvince[] = [
  { plateCode: 1, name: "Adana" },
  { plateCode: 2, name: "Adıyaman" },
  { plateCode: 3, name: "Afyonkarahisar" },
  { plateCode: 4, name: "Ağrı" },
  { plateCode: 5, name: "Amasya" },
  { plateCode: 6, name: "Ankara" },
  { plateCode: 7, name: "Antalya" },
  { plateCode: 8, name: "Artvin" },
  { plateCode: 9, name: "Aydın" },
  { plateCode: 10, name: "Balıkesir" },
  { plateCode: 11, name: "Bilecik" },
  { plateCode: 12, name: "Bingöl" },
  { plateCode: 13, name: "Bitlis" },
  { plateCode: 14, name: "Bolu" },
  { plateCode: 15, name: "Burdur" },
  { plateCode: 16, name: "Bursa" },
  { plateCode: 17, name: "Çanakkale" },
  { plateCode: 18, name: "Çankırı" },
  { plateCode: 19, name: "Çorum" },
  { plateCode: 20, name: "Denizli" },
  { plateCode: 21, name: "Diyarbakır" },
  { plateCode: 22, name: "Edirne" },
  { plateCode: 23, name: "Elazığ" },
  { plateCode: 24, name: "Erzincan" },
  { plateCode: 25, name: "Erzurum" },
  { plateCode: 26, name: "Eskişehir" },
  { plateCode: 27, name: "Gaziantep" },
  { plateCode: 28, name: "Giresun" },
  { plateCode: 29, name: "Gümüşhane" },
  { plateCode: 30, name: "Hakkari" },
  { plateCode: 31, name: "Hatay" },
  { plateCode: 32, name: "Isparta" },
  { plateCode: 33, name: "Mersin" },
  { plateCode: 34, name: "İstanbul" },
  { plateCode: 35, name: "İzmir" },
  { plateCode: 36, name: "Kars" },
  { plateCode: 37, name: "Kastamonu" },
  { plateCode: 38, name: "Kayseri" },
  { plateCode: 39, name: "Kırklareli" },
  { plateCode: 40, name: "Kırşehir" },
  { plateCode: 41, name: "Kocaeli" },
  { plateCode: 42, name: "Konya" },
  { plateCode: 43, name: "Kütahya" },
  { plateCode: 44, name: "Malatya" },
  { plateCode: 45, name: "Manisa" },
  { plateCode: 46, name: "Kahramanmaraş" },
  { plateCode: 47, name: "Mardin" },
  { plateCode: 48, name: "Muğla" },
  { plateCode: 49, name: "Muş" },
  { plateCode: 50, name: "Nevşehir" },
  { plateCode: 51, name: "Niğde" },
  { plateCode: 52, name: "Ordu" },
  { plateCode: 53, name: "Rize" },
  { plateCode: 54, name: "Sakarya" },
  { plateCode: 55, name: "Samsun" },
  { plateCode: 56, name: "Siirt" },
  { plateCode: 57, name: "Sinop" },
  { plateCode: 58, name: "Sivas" },
  { plateCode: 59, name: "Tekirdağ" },
  { plateCode: 60, name: "Tokat" },
  { plateCode: 61, name: "Trabzon" },
  { plateCode: 62, name: "Tunceli" },
  { plateCode: 63, name: "Şanlıurfa" },
  { plateCode: 64, name: "Uşak" },
  { plateCode: 65, name: "Van" },
  { plateCode: 66, name: "Yozgat" },
  { plateCode: 67, name: "Zonguldak" },
  { plateCode: 68, name: "Aksaray" },
  { plateCode: 69, name: "Bayburt" },
  { plateCode: 70, name: "Karaman" },
  { plateCode: 71, name: "Kırıkkale" },
  { plateCode: 72, name: "Batman" },
  { plateCode: 73, name: "Şırnak" },
  { plateCode: 74, name: "Bartın" },
  { plateCode: 75, name: "Ardahan" },
  { plateCode: 76, name: "Iğdır" },
  { plateCode: 77, name: "Yalova" },
  { plateCode: 78, name: "Karabük" },
  { plateCode: 79, name: "Kilis" },
  { plateCode: 80, name: "Osmaniye" },
  { plateCode: 81, name: "Düzce" },
];

export function turkeyProvinceRefCode(plateCode: number): string {
  return `TR-${plateCode}`;
}
