// Seyahat kategorisi (mobil) — dünya ülkelerinin Türkçe isim listesi.
// Web'in `src/lib/travel/world-country-codes.ts`'i `Intl.DisplayNames`'i
// ÇALIŞMA ANINDA çağırıyordu — bu, tarayıcıda sorunsuz ama bu ortamdaki
// Hermes/Expo Go çalışma zamanında DESTEKLENMİYOR ("Cannot read property
// 'prototype' of undefined", modül yüklenirken TÜM uygulamayı çökertiyordu,
// gerçek simulator testinde bulundu). Çözüm: isimler ÖNCEDEN (bu makinenin
// tam ICU'lu Node'uyla, `Intl.DisplayNames(['tr'],{type:'region'})`
// çalıştırılarak) STATİK olarak üretildi — artık çalışma zamanında Intl'e
// hiç ihtiyaç yok, RN/Hermes uyumluluğu garanti. ISO 3166-1 alpha-2 koddan
// Türkçe isme eşleme, ~250 ülke/bölge.
export const ALPHA2_TO_TURKISH_NAME: Record<string, string> = {
  "AF": "Afganistan", "AL": "Arnavutluk", "AQ": "Antarktika",
  "DZ": "Cezayir", "AS": "Amerikan Samoası", "AD": "Andorra",
  "AO": "Angola", "AG": "Antigua ve Barbuda", "AZ": "Azerbaycan",
  "AR": "Arjantin", "AU": "Avustralya", "AT": "Avusturya",
  "BS": "Bahamalar", "BH": "Bahreyn", "BD": "Bangladeş",
  "AM": "Ermenistan", "BB": "Barbados", "BE": "Belçika",
  "BM": "Bermuda", "BT": "Butan", "BO": "Bolivya",
  "BA": "Bosna-Hersek", "BW": "Botsvana", "BV": "Bouvet Adası",
  "BR": "Brezilya", "BZ": "Belize", "IO": "Britanya Hint Okyanusu Toprakları",
  "SB": "Solomon Adaları", "VG": "Britanya Virjin Adaları", "BN": "Brunei",
  "BG": "Bulgaristan", "MM": "Myanmar (Burma)", "BI": "Burundi",
  "BY": "Belarus", "KH": "Kamboçya", "CM": "Kamerun",
  "CA": "Kanada", "CV": "Cabo Verde", "KY": "Cayman Adaları",
  "CF": "Orta Afrika Cumhuriyeti", "LK": "Sri Lanka", "TD": "Çad",
  "CL": "Şili", "CN": "Çin", "TW": "Tayvan",
  "CX": "Christmas Adası", "CC": "Cocos (Keeling) Adaları", "CO": "Kolombiya",
  "KM": "Komorlar", "YT": "Mayotte", "CG": "Kongo - Brazavil",
  "CD": "Kongo - Kinşasa", "CK": "Cook Adaları", "CR": "Kosta Rika",
  "HR": "Hırvatistan", "CU": "Küba", "CY": "Kıbrıs",
  "CZ": "Çekya", "BJ": "Benin", "DK": "Danimarka",
  "DM": "Dominika", "DO": "Dominik Cumhuriyeti", "EC": "Ekvador",
  "SV": "El Salvador", "GQ": "Ekvator Ginesi", "ET": "Etiyopya",
  "ER": "Eritre", "EE": "Estonya", "FO": "Faroe Adaları",
  "FK": "Falkland Adaları", "GS": "Güney Georgia ve Güney Sandwich Adaları", "FJ": "Fiji",
  "FI": "Finlandiya", "AX": "Åland Adaları", "FR": "Fransa",
  "GF": "Fransız Guyanası", "PF": "Fransız Polinezyası", "TF": "Fransız Güney Toprakları",
  "DJ": "Cibuti", "GA": "Gabon", "GE": "Gürcistan",
  "GM": "Gambiya", "PS": "Filistin Bölgeleri", "DE": "Almanya",
  "GH": "Gana", "GI": "Cebelitarık", "KI": "Kiribati",
  "GR": "Yunanistan", "GL": "Grönland", "GD": "Grenada",
  "GP": "Guadeloupe", "GU": "Guam", "GT": "Guatemala",
  "GN": "Gine", "GY": "Guyana", "HT": "Haiti",
  "HM": "Heard Adası ve McDonald Adaları", "VA": "Vatikan", "HN": "Honduras",
  "HK": "Çin Hong Kong ÖİB", "HU": "Macaristan", "IS": "İzlanda",
  "IN": "Hindistan", "ID": "Endonezya", "IR": "İran",
  "IQ": "Irak", "IE": "İrlanda", "IL": "İsrail",
  "IT": "İtalya", "CI": "Côte d’Ivoire", "JM": "Jamaika",
  "JP": "Japonya", "KZ": "Kazakistan", "JO": "Ürdün",
  "KE": "Kenya", "KP": "Kuzey Kore", "KR": "Güney Kore",
  "KW": "Kuveyt", "KG": "Kırgızistan", "LA": "Laos",
  "LB": "Lübnan", "LS": "Lesotho", "LV": "Letonya",
  "LR": "Liberya", "LY": "Libya", "LI": "Liechtenstein",
  "LT": "Litvanya", "LU": "Lüksemburg", "MO": "Çin Makao ÖİB",
  "MG": "Madagaskar", "MW": "Malavi", "MY": "Malezya",
  "MV": "Maldivler", "ML": "Mali", "MT": "Malta",
  "MQ": "Martinik", "MR": "Moritanya", "MU": "Mauritius",
  "MX": "Meksika", "MC": "Monako", "MN": "Moğolistan",
  "MD": "Moldova", "ME": "Karadağ", "MS": "Montserrat",
  "MA": "Fas", "MZ": "Mozambik", "OM": "Umman",
  "NA": "Namibya", "NR": "Nauru", "NP": "Nepal",
  "NL": "Hollanda", "CW": "Curaçao", "AW": "Aruba",
  "SX": "Sint Maarten", "BQ": "Karayip Hollandası", "NC": "Yeni Kaledonya",
  "VU": "Vanuatu", "NZ": "Yeni Zelanda", "NI": "Nikaragua",
  "NE": "Nijer", "NG": "Nijerya", "NU": "Niue",
  "NF": "Norfolk Adası", "NO": "Norveç", "MP": "Kuzey Mariana Adaları",
  "UM": "ABD Küçük Harici Adaları", "FM": "Mikronezya", "MH": "Marshall Adaları",
  "PW": "Palau", "PK": "Pakistan", "PA": "Panama",
  "PG": "Papua Yeni Gine", "PY": "Paraguay", "PE": "Peru",
  "PH": "Filipinler", "PN": "Pitcairn Adaları", "PL": "Polonya",
  "PT": "Portekiz", "GW": "Gine-Bissau", "TL": "Timor-Leste",
  "PR": "Porto Riko", "QA": "Katar", "RE": "Reunion",
  "RO": "Romanya", "RU": "Rusya", "RW": "Ruanda",
  "BL": "Saint Barthelemy", "SH": "Saint Helena", "KN": "Saint Kitts ve Nevis",
  "AI": "Anguilla", "LC": "Saint Lucia", "MF": "Saint Martin",
  "PM": "Saint Pierre ve Miquelon", "VC": "Saint Vincent ve Grenadinler", "SM": "San Marino",
  "ST": "Sao Tome ve Principe", "SA": "Suudi Arabistan", "SN": "Senegal",
  "RS": "Sırbistan", "SC": "Seyşeller", "SL": "Sierra Leone",
  "SG": "Singapur", "SK": "Slovakya", "VN": "Vietnam",
  "SI": "Slovenya", "SO": "Somali", "ZA": "Güney Afrika",
  "ZW": "Zimbabve", "ES": "İspanya", "SS": "Güney Sudan",
  "SD": "Sudan", "EH": "Batı Sahra", "SR": "Surinam",
  "SJ": "Svalbard ve Jan Mayen", "SZ": "Esvatini", "SE": "İsveç",
  "CH": "İsviçre", "SY": "Suriye", "TJ": "Tacikistan",
  "TH": "Tayland", "TG": "Togo", "TK": "Tokelau",
  "TO": "Tonga", "TT": "Trinidad ve Tobago", "AE": "Birleşik Arap Emirlikleri",
  "TN": "Tunus", "TR": "Türkiye", "TM": "Türkmenistan",
  "TC": "Turks ve Caicos Adaları", "TV": "Tuvalu", "UG": "Uganda",
  "UA": "Ukrayna", "MK": "Kuzey Makedonya", "EG": "Mısır",
  "GB": "Birleşik Krallık", "GG": "Guernsey", "JE": "Jersey",
  "IM": "Man Adası", "TZ": "Tanzanya", "US": "Amerika Birleşik Devletleri",
  "VI": "ABD Virjin Adaları", "BF": "Burkina Faso", "UY": "Uruguay",
  "UZ": "Özbekistan", "VE": "Venezuela", "WF": "Wallis ve Futuna",
  "WS": "Samoa", "YE": "Yemen", "ZM": "Zambiya",
};

export function worldCountryTurkishName(alpha2: string): string {
  return ALPHA2_TO_TURKISH_NAME[alpha2] ?? alpha2;
}
