// Seyahat kategorisi — Türkiye il haritası (borders-of-turkey/lvl1-TR.geojson,
// CC0, mapshaper ile %4'e sadeleştirilip topojson'a çevrildi, bkz.
// src/lib/travel/turkey-provinces-topo.json). GeoJSON'ın KML kaynaklı
// "Name" alanı tutarsız bir transliterasyon kullanıyor (örn. "Agri",
// "K. Maras", "Kinkkale" — plaka bazlı isimlendirmeyle birebir uyuşmuyor).
// UI'da HER ZAMAN packages/shared/src/travelGeo.ts'teki kanonik Türkçe
// isim gösteriliyor — bu tablo sadece geometriyi plaka koduna bağlamak
// için var, 81 ilin tamamı elle karşılaştırılıp doğrulandı.
export const TURKEY_GEO_NAME_TO_PLATE_CODE: Record<string, number> = {
  Adana: 1,
  Adiyaman: 2,
  Afyon: 3,
  Agri: 4,
  Aksaray: 68,
  Amasya: 5,
  Ankara: 6,
  Antalya: 7,
  Ardahan: 75,
  Artvin: 8,
  Aydin: 9,
  Balikesir: 10,
  Bartin: 74,
  Batman: 72,
  Bayburt: 69,
  Bilecik: 11,
  "Bingöl": 12,
  Bitlis: 13,
  Bolu: 14,
  Burdur: 15,
  Bursa: 16,
  "Çanakkale": 17,
  "Çankiri": 18,
  "Çorum": 19,
  Denizli: 20,
  Diyarbakir: 21,
  "Düzce": 81,
  Edirne: 22,
  Elazig: 23,
  Erzincan: 24,
  Erzurum: 25,
  Eskisehir: 26,
  Gaziantep: 27,
  Giresun: 28,
  "Gümüshane": 29,
  Hakkari: 30,
  Hatay: 31,
  Igdir: 76,
  Isparta: 32,
  Istanbul: 34,
  Izmir: 35,
  "K. Maras": 46,
  "Karabük": 78,
  Karaman: 70,
  Kars: 36,
  Kastamonu: 37,
  Kayseri: 38,
  Kilis: 79,
  Kinkkale: 71,
  Kirklareli: 39,
  Kirsehir: 40,
  Kocaeli: 41,
  Konya: 42,
  "Kütahya": 43,
  Malatya: 44,
  Manisa: 45,
  Mardin: 47,
  Mersin: 33,
  Mugla: 48,
  Mus: 49,
  Nevsehir: 50,
  Nigde: 51,
  Ordu: 52,
  Osmaniye: 80,
  Rize: 53,
  Sakarya: 54,
  Samsun: 55,
  Sanliurfa: 63,
  Siirt: 56,
  Sinop: 57,
  Sirnak: 73,
  Sivas: 58,
  Tekirdag: 59,
  Tokat: 60,
  Trabzon: 61,
  Tunceli: 62,
  Usak: 64,
  Van: 65,
  Yalova: 77,
  Yozgat: 66,
  Zinguldak: 67,
};

export function turkeyGeoNamePlateCode(geoName: string): number | null {
  return TURKEY_GEO_NAME_TO_PLATE_CODE[geoName] ?? null;
}
